Repository GeOsmFamily/geosm-frontend-final, pull requests merged in 2021-09, with the labels that each got.

#164 fix zoom share point & fix bug share map tool
  package-lock.json
  package.json
  src/app/components/header/search/handle/handle-nominatim-search.ts
  src/app/components/header/search/search.component.scss
  src/app/components/map/map.component.ts
  src/app/components/map/vertical-toolbar/vertical-toolbar.component.ts
  src/app/components/modal/info-modal/info-modal.component.html
  src/app/services/share/share-service.service.ts
Labels: bug, Update

#166 BorisGautier/issue163
  .gitignore
  README.md
  geosm.png
  src/app/components/map/map.component.ts
Labels: documentation

#165 Spanish version
  .gitignore
  README.md
  geosm.png
  package-lock.json
  package.json
  src/app/components/header/search/handle/handle-nominatim-search.ts
  src/app/components/header/search/search.component.scss
  src/app/components/map/map.component.ts
  src/app/components/map/vertical-toolbar/vertical-toolbar.component.ts
  src/app/components/modal/info-modal/info-modal.component.html
  src/app/services/share/share-service.service.ts
Labels: bug, documentation

#167 Add Metrics
  .firebaserc
  angular.json
  firebase.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/button-sheet/button-sheet/button-sheet.component.ts
  src/app/components/header/search/handle/handle-emprise-search.ts
  src/app/components/header/search/handle/handle-layer-search.ts
  src/app/components/header/search/handle/handle-nominatim-search.ts
  src/app/components/header/search/search.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/vertical-page-left/vertical-page-principal/vertical-page-principal.component.ts
  src/app/components/map/vertical-page-left/vertical-page-secondaire/groupe-carte/carte-thematique/carte-thematique.component.ts
  src/app/components/map/vertical-page-left/vertical-page-secondaire/liste-thematique/liste-thematique/liste-thematique.component.ts
  src/app/components/map/vertical-page-right/download/download.component.ts
  src/app/components/map/vertical-page-right/map-tools/draw/draw.component.ts
  src/app/components/map/vertical-page-right/map-tools/measure/measure.component.ts
  src/app/components/map/vertical-page-right/map-tools/print/print.component.ts
  src/app/components/map/vertical-page-right/routing/routing.component.ts
  src/app/components/map/vertical-toolbar/vertical-toolbar.component.ts
  src/app/interfaces/analyticsInterface.ts
  src/app/interfaces/viewsInterface.ts
  src/app/services/analytics/analytics.service.spec.ts
  src/app/services/analytics/analytics.service.ts
  src/environments/environment-example.ts
Labels: enhancement, Update

#168 Dev
  .firebaserc
  angular.json
  firebase.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/button-sheet/button-sheet/button-sheet.component.ts
  src/app/components/header/search/handle/handle-emprise-search.ts
  src/app/components/header/search/handle/handle-layer-search.ts
  src/app/components/header/search/handle/handle-nominatim-search.ts
  src/app/components/header/search/search.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/vertical-page-left/vertical-page-principal/vertical-page-principal.component.ts
  src/app/components/map/vertical-page-left/vertical-page-secondaire/groupe-carte/carte-thematique/carte-thematique.component.ts
  src/app/components/map/vertical-page-left/vertical-page-secondaire/liste-thematique/liste-thematique/liste-thematique.component.ts
  src/app/components/map/vertical-page-right/download/download.component.ts
  src/app/components/map/vertical-page-right/map-tools/draw/draw.component.ts
  src/app/components/map/vertical-page-right/map-tools/measure/measure.component.ts
  src/app/components/map/vertical-page-right/map-tools/print/print.component.ts
  src/app/components/map/vertical-page-right/routing/routing.component.ts
  src/app/components/map/vertical-toolbar/vertical-toolbar.component.ts
  src/app/interfaces/analyticsInterface.ts
  src/app/interfaces/viewsInterface.ts
  src/app/services/analytics/analytics.service.spec.ts
  src/app/services/analytics/analytics.service.ts
  src/environments/environment-example.ts
Labels: enhancement, Update

#169 Merge pull request #167 from GeOsmFamily:BorisGautier/issue38
  src/app/services/analytics/analytics.service.ts
Labels: Update

#173 BorisGautier/issue171
  src/index.html
Labels: Update

#174 BorisGautier/issue172
  README.md
  src/assets/i18n/es.json
  src/environments/environment-example.ts
Labels: documentation, Update

#175 Dev
  .firebaserc
  .gitignore
  README.md
  firebase.json
  src/assets/i18n/es.json
  src/environments/environment-example.ts
  src/index.html
Labels: bug, documentation, Update

#176 update kpi
  src/app/services/analytics/analytics.service.ts
Labels: bug, Update
